apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: k8s-gateway
    repo: https://ori-edge.github.io/k8s_gateway/
    version: 2.4.0
    releaseName: "k8s-gateway"
    includeCRDs: true
    namespace: network
    valuesFile: values.yaml
