apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: k8s-gateway
    repo: https://k8s-gateway.github.io/k8s_gateway/
    version:  3.2.3
    releaseName: "k8s-gateway"
    includeCRDs: true
    namespace: network
    valuesFile: values.yaml
