apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-doppler
  namespace: flux-system
spec:
  path: './kubernetes/apps/flux-system/addons/external-secrets/doppler/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: doppler-token-auth-api
      namespace: flux-system
