apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netshoot
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: nicolaka/netshoot
      tag: latest
    command:
      - /bin/sh
      - -c
      - sleep infinity
    service:
      main:
        enabled: false
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
