---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cert-manager
  target:
    name: cloudflare-token-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        cloudflare-token: "{{ .TOKEN }}"
  data:
    - secretKey: TOKEN
      remoteRef:
        key: TOKEN
