---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: &name cert-manager
  namespace: cert-manager
spec:
  provider:
    doppler:
      project: *name
      config: dev
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: flux-system
