fullnameOverride: externaldns-internal

domainFilters:
  - kubelab.fi

env:
  - name: EXTERNAL_DNS_RFC2136_HOST
    value: "172.16.9.3"
  - name: EXTERNAL_DNS_RFC2136_PORT
    value: "53"
  - name: EXTERNAL_DNS_RFC2136_ZONE
    value: "kubelab.fi"
  - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
    value: "true"
  - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
    value: externaldns
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
    valueFrom:
      secretKeyRef:
        name: externaldns-internal-secrets
        key: bind_rndc_algorithm
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: externaldns-internal-secrets
        key: bind_rndc_secret

podAnnotations:
  secret.reloader.stakater.com/reload: externaldns-internal-secrets

policy: sync
provider: rfc2136

resources:
  requests:
    cpu: 16m
    memory: 90M
  limits:
    memory: 90M

serviceMonitor:
  enabled: true

sources:
  - ingress
  - crd

txtPrefix: "k8s-dev."
extraArgs:
  - --ingress-class=internal-nginx
