apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking


helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s/helm/
    version: 3.7.3
    releaseName: "kubernetes-schemas"
    namespace: networking
    valuesFile: values.yaml
