controllers:
  main:
    pod:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: kubernetes-schemas
    containers:
      main:
        image:
          repository: ghcr.io/samip5/dev-kubernetes-schemas
          tag: latest@sha256:fa8c9d493f82325fa30b92cc63a33066cdc54a2ae40ef2a284a80649849f2494
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            memory: 100Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    className: nginx
    hosts:
      - host: "schemas.kubelab.fi"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
