---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cilium
  path: ./kubernetes/apps/kube-system/cilium/config
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m

