apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/samip5/k8s-dev-cluster.git'
    - 'https://argoproj.github.io/argo-helm'
    - 'https://helm.cilium.io/*'
    - 'https://emberstack.github.io/helm-charts'
    - 'https://1password.github.io/connect-helm-charts'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'cilium-secrets'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: '1pass'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
