apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: 7.1.288
    releaseName: "reflector"
    includeCRDs: true
    namespace: kube-system
