apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: 9.1.8
    releaseName: "reflector"
    includeCRDs: true
    namespace: kube-system
