apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:UADH4tuURbDrJeUtOnt1Gp5Xzel5AaAESmt1Ylk1FZA5qpuvvnZzdN8Y6XXNwOc0nRCROal9JAhW+sz6,iv:x10rANQmLKSqyg7LdVBaQxmYnsKLsmqPogr/JcwOPng=,tag:ocGfilrT8vh72DT9T6bkwA==,type:str]
    username: ENC[AES256_GCM,data:38LHR8I=,iv:ITUyDKsMRvlk9L2AGHCe7As0en6/uLC7onku50Nr9Qo=,tag:eaqy4EA0R+qClx/E7loJwA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kyu4t3wc94687gy4pw58jdnftckwh2ewpnqrqd2jvu9wvwa3sf3qywmgap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOTdLNkkra2hPTCt2UEFI
            MC9mQ1JzZ0lMOW40TmNtRmJFRmtTOXJlMmhzCm1aZStVcng3WUJRSWtic2NDdUZt
            UjJtZUxoZHRKUFNRUm1rUGQ0aTlJMUkKLS0tIEpIRzJUOU1weEZOYUdaK2tRZGJD
            d2UwRmtNR0RpVVU2blBoYkJxdzdXdTQK5YqVbzHBg6CVLmHPHDK1PsUz8MnlMQsE
            q2/PNWvRrQUdAyh3Z94PLcv8j6RHlAQiThqr55SkotDBDQb2oQ/lLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T08:14:30Z"
    mac: ENC[AES256_GCM,data:uJLDFqNYP22k3NUMURbIn4YCuqGaPWZvjbjovQOhEg77NVmEEvov3cU1AGS8DBzzm8g7hsLcRo7J0cPEZ7ZqJywN/99oOfTWUUOSZjTUv+oPwdk4mLjdcPYQ/EnxqayY8fm7YxjcQTnCO4XBo8RUUEDjV5j7/PabOY0KKWxdZMQ=,iv:i0jr1qnsTljWZCMh7AI3ytYylNQfrKmSBsp2A0YqKOg=,tag:CKNlMwn40mszrxk402dAxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
