apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubelab
  namespace: gateway
  annotations:
    cert-manager.io/issuer: letsencrypt-production
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: "10.46.2.43,2001:14ba:16fd:961d::e443"
      external-dns.alpha.kubernetes.io/hostname: "ingress.kubelab.fi"
  listeners:
    - protocol: HTTPS
      port: 443
      name: https
      hostname: "*.kubelab.fi"
      tls:
        certificateRefs:
          - kind: Secret
            name: kubelab-fi-production-tls
            namespace: networking
      allowedRoutes:
        namespaces:
          from: All
