apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    version: 1.35.1
    releaseName: "coredns"
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml
