apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
  labels:
    dev.stonegarden: external-dns
spec:
  generators:
    - git:
        repoURL: https://github.com/samip5/k8s-dev-cluster.git
        revision: HEAD
        directories:
          - path: kubernetes/infra/network/external-dns/*
  template:
    metadata:
      name: 'external-dns-{{ path.basename }}'
      labels:
        dev.stonegarden: external-dns
    spec:
      project: external-dns
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/samip5/k8s-dev-cluster.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
