apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  dev.stonegarden: external-dns
  app.kubernetes.io/managed-by: argocd

resources:
  - project.yaml
  - application-set.yaml
  - dnsendpoint-crd.yaml
