apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: "linux"
  bgpInstances:
    - name: cluster
      localASN: 213021
      peers:
        - name: opnsense
          peerASN: 213021
          peerAddress: fd9d:7a72:44eb:d::1
          peerConfigRef:
            name: cilium-peer-v6
        - name: opnsense-v4
          peerASN: 213021
          peerAddress: 10.0.110.1
          peerConfigRef:
            name: cilium-peer-v4
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer-v4
spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer-v6
spec:
  families:
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ExternalIP
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
    - advertisementType: "PodCIDR"
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: [ "never-used-value" ] }

