---
autoDirectNodeRoutes: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  id: 3
  name: dev
enableRuntimeDeviceDetection: true
endpointRoutes:
  enabled: true
envoy:
  enabled: false
hubble:
  enabled: true
  tls:
    insecure: true
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095 # 3 years
      certManagerIssuerRef:
        group: "cert-manager.io"
        kind: "ClusterIssuer"
        name: "selfsigned-issuer"
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: false
    dashboards:
      enabled: false
      label: grafana_dashboard
      namespace: monitoring
      labelValue: "1"
      annotations: { }
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      className: "cilium"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - &host "hubble.kubelab.fi"
      tls:
        - hosts:
            - *host
          secretName: hubble-tls
gatewayAPI:
  enabled: true

ingressController:
  enabled: false
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 10.46.2.80
    insecureNodePort: 32434
    secureNodePort: 31247
ipam:
  mode: kubernetes
bgpControlPlane:
  enabled: true
ipv4NativeRoutingCIDR: "10.42.0.0/16"
ipv6NativeRoutingCIDR: "2001:67c:1104:d000::/56"
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
ipv6:
  enabled: true
enableIPv6Masquerade: true
operator:
  rollOutPods: true
  replicas: 1
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
