
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres17
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4-13
  primaryUpdateStrategy: unsupervised
  storage:
    size: 25Gi
    storageClass: local-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  resources:
    requests:
      memory: 1.5Gi
    limits:
      memory: 2Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB

  monitoring:
    enablePodMonitor: false
  backup:
    retentionPolicy: "30d"
