apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking

resources:
  - certificates/prod.yaml
  - certificates/allow-ref.yaml

helmCharts:
  - name: ingress-nginx
    releaseName: nginx
    namespace: networking
    repo: https://kubernetes.github.io/ingress-nginx/
    version: 4.11.3
    valuesFile: values.yaml
