---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: traefik/whoami
      tag: v1.10.2

    service:
      main:
        ports:
          http:
            enabled: true
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: cilium
        hosts:
          - host: &host who.${SECRET_DOMAIN}
            paths:
              - path: /

        tls:
          - hosts:
              -  *host



    resources:
      requests:
        cpu: 15m
        memory: 50M
      limits:
        memory: 100M
