apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: databases
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts/
    targetRevision: 0.26.0
    helm:
      valuesObject:
        crds:
          create: true
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
