apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - generator.yaml

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.16.1
    releaseName: "external-dns-cloudflare"
    includeCRDs: true
    namespace: network
    valuesFile: values.yaml
