apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cyberchef
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: registry.samipsolutions.fi/docker/mpepping/cyberchef
      tag: v10.18.6
    env:
      TZ: ${TZ}
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: "cilium"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: hammer-wrench
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
