apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/samip5/k8s-dev-cluster.git'
    - 'https://charts.goauthentik.io'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'security'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

