---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kubelab-fi-production"
  namespace: networking
spec:
  secretName: "kubelab-fi-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "kubelab.fi"
  dnsNames:
    - "kubelab.fi"
    - "*.kubelab.fi"
