---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kubelab-fi-production"
  namespace: networking
spec:
  secretName: "kubelab-fi-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "kubelab.fi"
  dnsNames:
    - "kubelab.fi"
    - "*.kubelab.fi"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "gateway"
