---
# yaml-language-server: $schema=https://kubernetes-schemas.skylab.fi/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.12-1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-secret
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
