clusterName: dev
# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.8.0-alpha.1
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.30.2

cniConfig:
   name: none

endpoint: https://10.0.110.5:6443
domain: dev.local
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - "127.0.0.1"
  - "10.0.110.18"
additionalApiServerCertSans:
  - dev.local
  - cluster.local
clusterPodNets:
  - 10.42.0.0/16
  - 2001:14ba:7429:a4f0::/60
clusterSvcNets:
  - 10.43.0.0/16
  - 2001:14ba:7429:a400::10d:0/112
nodes:
 - hostname: m1
   ipAddress: 10.0.110.18
   installDisk: /dev/sda
   disableSearchDomain: true
   controlPlane: true
   noSchematicValidate: true
   schematic:
     overlay:
       name: sbc-raspberrypi
       image: registry.skysolutions.fi/library/sbc-raspberrypi:alpha.1-1@sha256:f5734630fbae0647daf6e490ff91cd5f95220c3fc34e64364b2f245cde502a43
   talosImageURL: registry.skysolutions.fi/library/talos/installer
   networkInterfaces:
     - interface: bond0
       bond:
         mode: active-backup
         interfaces:
           - enxe45f011b3298
       dhcp: true
       routes:
         - network: "::/0"
           gateway: "fd9d:7a72:44eb:d::1"
           metric: 1
       dhcpOptions:
         routeMetric: 4000
       vip:
         ip: 10.0.110.5
 - hostname: w1
   ipAddress: 10.0.110.19
   installDisk: /dev/sda
   controlPlane: false
   noSchematicValidate: true
   schematic:
     overlay:
       name: sbc-raspberrypi
       image: registry.skysolutions.fi/library/sbc-raspberrypi:alpha.1-1@sha256:f5734630fbae0647daf6e490ff91cd5f95220c3fc34e64364b2f245cde502a43
 - hostname: w2
   ipAddress: 10.0.110.20
   installDisk: /dev/sda
   controlPlane: false
   noSchematicValidate: true
   schematic:
     overlay:
       name: sbc-raspberrypi
       image: registry.skysolutions.fi/library/sbc-raspberrypi:alpha.1-1@sha256:f5734630fbae0647daf6e490ff91cd5f95220c3fc34e64364b2f245cde502a43
   talosImageURL: registry.skysolutions.fi/library/talos/installer
   networkInterfaces:
     - interface: bond0
       bond:
         mode: active-backup
         interfaces:
           - enxe45f011b3293
       dhcp: true
       routes:
         - network: "::/0"
           gateway: "fd9d:7a72:44eb:d::1"
           metric: 1
       dhcpOptions:
         routeMetric: 4000




patches:
  - "@./patches/global/cluster-discovery.yaml"
  - "@./patches/global/containerd.yaml"
  - "@./patches/global/disable-search-domain.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/nfs.yaml"
  - "@./patches/global/sysctl.yaml"
  - "@./patches/global/disable-kexec.yaml"

controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/disable-admission-controller.yaml"
    - "@./patches/controller/kube-prism.yaml"
