global:
  domain: argocd.kubelab.fi
  dualStack:
    ipFamilyPolicy: PreferDualStack
    ipFamilies: ["IPv6","IPv4"]

configs:
  cm:
    create: true
    application.resourceTrackingMethod: "annotation+label"
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
  cmp:
    create: true
    plugins:
      kustomize-build-with-helm:
        generate:
          command: [ "sh", "-c" ]
          args: [ "kustomize build --enable-helm" ]
    secret:
      githubSecret: "$argocd-webhook-secret:webhook"

crds:
  install: true
  # -- Keep CRDs on chart uninstall
  keep: false

server:
  ingress:
    enabled: true
    hostname: "argocd.kubelab.fi"
    controller: generic
    ingressClassName: cilium
    tls: true
  certificate:
    enabled: true
    issuer:
      group: "cert-manager.io"
      kind: "ClusterIssuer"
      name: "letsencrypt-production"
    privateKey:
      algorithm: ECDSA
      size: 384


repoServer:
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.2
      command: [ "/bin/sh", "-c" ]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

  extraContainers:
    - name: kustomize-build-with-helm
      command:
        - argocd-cmp-server
      image: '{{ default .Values.global.image.repository .Values.repoServer.image.repository }}:{{ default (include "argo-cd.defaultTag" .) .Values.repoServer.image.tag }}'
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: cmp-kustomize-build-with-helm
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: kustomize-build-with-helm.yaml
        - mountPath: /tmp
          name: cmp-tmp
  volumes:
    - name: cmp-kustomize-build-with-helm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: { }
    - name: custom-tools
      emptyDir: { }
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
