global:
  domain: argocd.kubelab.fi
  dualStack:
    ipFamilyPolicy: PreferDualStack

configs:
  cm:
    create: true
    application.resourceTrackingMethod: "annotation+label"
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
  cmp:
    create: true
    plugins:
      kustomize-build-with-helm:
        generate:
          command: [ "sh", "-c" ]
          args: [ "kustomize build --enable-helm --enable-alpha-plugins --enable-exec" ]
    secret:
      githubSecret: "$argocd-webhook-secret:webhook"

crds:
  install: true
  keep: false

server:
  ingress:
    enabled: true
    controller: generic
    ingressClassName: cilium
    tls: true
  certificate:
    enabled: true
    issuer:
      group: "cert-manager.io"
      kind: "ClusterIssuer"
      name: "letsencrypt-production"
    privateKey:
      algorithm: ECDSA
      size: 384

repoServer:
  env:
    - name: XDG_CONFIG_HOME
      value: /home/argocd/.config
    - name: SOPS_AGE_KEY_FILE
      value: /home/argocd/.config/sops/age/keys.txt
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.2
      command: [ "/bin/sh", "-c" ]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

  extraContainers:
    - name: kustomize-build-with-helm
      env:
        - name: XDG_CONFIG_HOME
          value: /home/argocd/.config
        - name: SOPS_AGE_KEY_FILE
          value: /home/argocd/.config/sops/age/keys.txt
      command:
        - argocd-cmp-server
      image: '{{ default .Values.global.image.repository .Values.repoServer.image.repository }}:{{ default (include "argo-cd.defaultTag" .) .Values.repoServer.image.tag }}'
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: cmp-kustomize-build-with-helm
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: kustomize-build-with-helm.yaml
        - mountPath: /tmp
          name: cmp-tmp
        - mountPath: /usr/local/bin/ksops
          name: custom-tools
          subPath: ksops
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
        - mountPath: /home/argocd/.config/sops/age
          name: sops-age
  volumes:
    - name: cmp-kustomize-build-with-helm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: argocd-sops-age
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /home/argocd/.config/sops/age
      name: sops-age
