apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crd-reader-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: crd-reader
    namespace: kube-system
roleRef:
  kind: Role
  name: crd-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-reader-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: crd-reader
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: crd-reader-clusterrole
  apiGroup: rbac.authorization.k8s.io
