apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github

resources:
  - ns.yaml
#  - runners/k8s-dev-cluster.yaml

generators:
  - generator.yaml

helmCharts:
  - name: gha-runner-scale-set-controller
    releaseName: arc
    namespace: github
    repo: oci://ghcr.io/actions/actions-runner-controller-charts/
    version: 0.9.3
    includeCRDs: true
    valuesFile: values.yaml
