apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github

resources:
  - ns.yaml
  - runners/k8s-dev-cluster.yaml

generators:
  - generator.yaml

helmCharts:
  - name: actions-runner-controller
    releaseName: arc
    namespace: github
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    version: 0.23.7
    valuesFile: values.yaml
