apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github

resources:
- ns.yaml
- runners

generators:
- generator.yaml

helmCharts:
- includeCRDs: true
  name: gha-runner-scale-set-controller
  namespace: github
  releaseName: arc
  repo: oci://ghcr.io/actions/actions-runner-controller-charts/
  valuesFile: values.yaml
  version: 0.10.1
