apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/samip5/k8s-dev-cluster.git'
    - 'https://bugfest.github.io/tor-controller'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'cert-manager'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'tor'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

