apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github


helmCharts:
  - name: gha-runner-scale-set
    releaseName: arc-cluster
    namespace: github
    repo: oci://ghcr.io/actions/actions-runner-controller-charts/
    version: 0.10.1
    includeCRDs: true
    valuesFile: values.yaml
