runnerScaleSetName: arc-cluster
runnerGroup: default

githubConfigUrl: https://github.com/samip5/k8s-dev-cluster

minRunners: 1
maxRunners: 4

containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/joryirving/actions-runner:2.325.0
        command: [ "/home/runner/run.sh" ]

controllerServiceAccount:
  namespace: github
  name: gha-rs-controller

githubConfigSecret: controller-manager
