---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: "ingress.kubelab.fi"
spec:
  endpoints:
    - dnsName: "ingress.kubelab.fi"
      recordType: CNAME
      targets: ["daa31376-2a34-4393-ae1d-4190b73de357.cfargotunnel.com"]
