apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true

generators:
  - generator.yaml
resources:
  - dnsendpoint.yaml


helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s/helm/
    version: 3.4.0
    releaseName: "cloudflared"
    namespace: network
    valuesFile: values.yaml
