apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QjcWWDhkD2BJ+wDpwDOJ,iv:HoBEcafvgRjuk51VfSOdAGohb1AH2O3dR2hyoVQWwM0=,tag:PFZVkXXo2Rf5d+nyzTQT4Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4B8v6jut4HLd535gDFuVYFbvFZbSIb3UwqHK6ivQKuGfmFLf,iv:XeSLKDJxuF9slbS2pP159gdxpHKH+zxYynoFt6K7UAA=,tag:HrHgoQCkdo1yAGNhVNFR7w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:C44r+zLjidWEyg==,iv:PzCdd40TXC/BQ4V8cR87Acxnl+vdrt21ngYtmKkruVQ=,tag:anNpxTcwRsediBk4/riicw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kyu4t3wc94687gy4pw58jdnftckwh2ewpnqrqd2jvu9wvwa3sf3qywmgap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UW0vTXdVQzFkcnVTaVIx
            V1M0TTlCVlphRXI0SC9PYzVtNnV4K0Yrb0FRClhXUjVScW1WS3JOM0YyS1NCei9R
            M3l5cmwreHpUVTJSN0oyMXdjditoMjQKLS0tIEsvcEdzQ1Y0Skw4WkpBVUZhN1E0
            Ym1VU1NwUExrYXVQZldWcXFvWnpSRG8K7M6FRZv6ZgAZEk0f2H3Y8x/zRrCR1xGG
            xO8Z9VFR2GJe/ymfYXYP85weRDzn1pVblvamA9X5c7oDPDcPIgrlfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T04:38:36Z"
    mac: ENC[AES256_GCM,data:byR3GAU4J++tbWe76xtOIC+Ez8ibtsiv2QuiCggBlAXPEkKaSlpN+FqOc9EMfYtNt9W4LpsSPHHM0Lvzp702KJLCxBSGkL9cqNU97bq38n9PYImKcpl/2wyNJoxecE9xN2e+LwaBtEMi40uNTuyJG0fXpQoW+4n65lywRN+vaYs=,iv:C/69T09aCngSFd3yAkHPKnE1Xx+ONbPIxfcSNR6czWw=,tag:YKC07rv8NLPkoSnwL4FfPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
