apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/samip5/k8s-dev-cluster.git'
    - 'https://ori-edge.github.io/k8s_gateway/'
    - 'https://argoproj.github.io/argo-helm'
  destinations:
#    - namespace: 'k8s-gateway'
#      server: '*'
    - namespace: 'argocd'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

