apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: argocd
  labels:
    dev.stonegarden: storage
spec:
  generators:
    - git:
        repoURL: https://github.com/samip5/k8s-dev-cluster.git
        revision: HEAD
        directories:
          - path: kubernetes/infra/storage/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: storage
    spec:
      project: storage
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/samip5/k8s-dev-cluster.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
