apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - http-route.yaml


helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s/helm/
    version: 3.5.0
    releaseName: "whoami"
    namespace: default
    valuesFile: values.yaml
