apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default


helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s/helm/
    version: 3.3.2
    releaseName: "whoami"
    namespace: default
    valuesFile: values.yaml
