apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-configsecrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik
        property: secret_key
