apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  destination:
    namespace: security
    server: https://kubernetes.default.svc
  project: security
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.2.4
    helm:
      valuesObject:
        server:
          ingress:
            enabled: false
        authentik:
          log_level: debug
        redis:
          enabled: true
          master:
            persistence:
              enabled: false
        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 17.4.0-debian-12-r15
          password:
            valueFrom:
              secretKeyRef:
                key: password
                name: authentik-postgresql
        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: authentik-configsecrets
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true

