apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  destination:
    namespace: security
    server: https://kubernetes.default.svc
  project: security
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.4.1
    helm:
      valuesObject:
        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: authentik-configsecrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: authentik-postgresql
        server:
          replicas: 1
          ingress:
            enabled: false
        worker:
          replicas: 0
        authentik:
          log_level: debug
          error_reporting:
            enabled: false
          postgresql:
            enabled: true
            name: "authentik"
            user: "authentik"
        redis:
          enabled: true
          master:
            persistence:
              enabled: false
        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 17.5.0-debian-12-r18
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

